enable-magisk-update = true
parallel-jobs = 1

# ============================================
# APENAS APPS HABILITADOS ESTÃO PRESENTES ABAIXO
# ============================================

[YouTube]
enabled = true
build-mode = "both"
arch = "arm64-v8a"
version = "auto"
# Fontes de download primárias e secundárias
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# A fonte 'archive' foi removida por ser instável
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube" # <--- REMOVIDO

[Music]
enabled = true
build-mode = "both"
arch = "arm64-v8a"
# Fontes de download primárias e secundárias
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# A fonte 'archive' foi removida por ser instável
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music" # <--- REMOVIDO
